###########################################################
## Deploy: kubectl -n [namespace] apply -f pod-hostpid-only.yaml 
## Access: kubectl -n [namespace] exec -it pod-hostpid -- bash
## Remove: kubectl -n [namespace] delete -f pod-hostpid-only.yaml
###########################################################
apiVersion: v1
kind: Pod
metadata:
  name: pod-hostpid
  labels:
    app: pentest
spec:
  hostPID: true
  containers:
  - image: ubuntu
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    name: hostpid
  # Force scheduling of your pod on control plane node by uncommenting this line and changing the name
  #nodeName: k8s-control-plane-node
