apiVersion: v1
kind: ReplicationController
metadata:
  name: priv-and-hostpid-exec-replicationcontroller
  labels:
    app: pentest
    type: replicationcontroller
spec:
  replicas: 2
  selector:
    app: pentest
    type: replicationcontroller
  template:
    metadata:
      labels:
        app: pentest
        type: replicationcontroller
    spec:
      hostPID: true
      containers:
      - name: priv-and-hostpid-exec-replicationcontroller
        image: ubuntu
        securityContext:
          privileged: true
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
      #nodeName: k8s-control-plane-node # Force your pod to run on the control-plane node by uncommenting this line and changing to a control-plane node name