###########################################################
## Deploy: kubectl -n [namespace] apply -f pod-hostipc.yaml 
## Access: kubectl -n [namespace] exec -it pod-hostipc -- bash
## Remove: kubectl -n [namespace] delete pod-hostipc
###########################################################
apiVersion: v1
kind: Pod
metadata:
  name: pod-hostipc
  labels:
    app: pentest
spec:
  hostIPC: true
  containers:
  - image: ubuntu
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    name: hostipc
    #nodeName: control-plane-node-name # Uncomment and change to control node name to try and schedule pod on control-plane node
