###########################################################
## Deploy:   kubectl apply -f everything-allowed-exec-statefulset.yaml
## Find Pod: kubectl get pods | grep everything-allowed-exec-statefulset 
## Access:   kubectl exec -it everything-allowed-exec-statefulset-ID -- chroot /host bash
## Remove:   kubectl delete statefulset everything-allowed-exec-statefulset
## Remove:   kubectl delete service everything-allowed-exec-service
###########################################################
apiVersion: v1
kind: Service
metadata:
  name: everything-allowed-exec-statefulset-service
  labels:
    app: pentest
spec:
  ports:
  - port: 4444
    name: everything-allowed-exec-statefulset-service
  clusterIP: None
  selector:
    app: pentest
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: everything-allowed-exec-statefulset
  labels:
    app: pentest
    type: statefulset
spec:
  serviceName: "pentest"
  replicas: 2
  selector:
    matchLabels:
      app: pentest
      type: statefulset
  template:
    metadata:
      labels:
        app: pentest
        type: statefulset
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      containers:
      - name: everything-allowed-exec-statefulset
        image: ubuntu
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /host
          name: noderoot
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
      #nodeName: k8s-control-plane-node # Force your pod to run on the control-plane node by uncommenting this line and changing to a control-plane node name
      volumes:
      - name: noderoot
        hostPath:
          path: /
      