###########################################################
## Deploy: kubectl -n [namespace] apply -f pod-everything-allowed.yaml 
## Access: kubectl -n [namespace] exec -it pod-everything-allowed -- bash
## Remove: kubectl -n [namespace] delete -f pod-everything-allowed.yaml 
## Credit: Adapted from https://raesene.github.io/blog/2019/04/01/The-most-pointless-kubernetes-command-ever/
###########################################################
apiVersion: v1
kind: Pod
metadata:
  name: pod-everything-allowed
  labels:
    app: everything-allowed
spec:
  hostNetwork: true
  hostPID: true
  hostIPC: true
  containers:
  - name: everything-allowed
    image: busybox
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /host
      name: noderoot
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
  # If you put the name of the master node below and uncomment this line, you can ensure your pod gets scheduled on the master node ()
  #nodeName: k8s-master
  volumes:
  - name: noderoot
    hostPath:
      path: /