###########################################################
## Deploy: kubectl -n [namespace] apply -f pod-everything-allowed.yaml 
## Access: kubectl -n [namespace] exec -it pod-everything-allowed -- bash
## Remove: kubectl -n [namespace] delete pod-everything-allowed
###########################################################
apiVersion: v1
kind: Pod
metadata:
  name: pod-everything-allowed
  labels:
    app: pentest
spec:
  hostNetwork: true
  hostPID: true
  hostIPC: true
  containers:
  - name: everything-allowed
    image: ubuntu
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /host
      name: noderoot
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    #nodeName: control-plane-node-name # Uncomment and change to control node name to try and schedule pod on control-plane node
  volumes:
  - name: noderoot
    hostPath:
      path: /