apiVersion: batch/v1
kind: Job
metadata:
  name: priv-and-hostpid-exec-job
  labels:
    app: pentest
    type: job
spec:
  template:
    spec:
      hostPID: true
      containers:
      - name: priv-and-hostpid-exec-job
        image: ubuntu
        securityContext:
          privileged: true
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
      #nodeName: k8s-control-plane-node # Force your pod to run on the control-plane node by uncommenting this line and changing to a control-plane node namerestartPolicy: OnFailure