###########################################################
## Deploy: kubectl apply -f priv-and-hostpid-exec-pod.yaml 
## Access: kubectl exec -it priv-and-hostpid-exec-pod -- chroot /host
## Remove: kubectl delete priv-and-hostpid-exec-pod
###########################################################
apiVersion: v1
kind: Pod
metadata:
  name: priv-and-hostpid-exec-pod
  labels:
    app: pentest
spec:
  hostPID: true
  containers:
  - name: priv-and-hostpid-pod
    image: ubuntu
    securityContext:
      privileged: true
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
  #nodeName: k8s-control-plane-node # Force your pod to run on the control-plane node by uncommenting this line and changing to a control-plane node name